### ISSUE TITLE
Rename file is not working

### ISSUE THREAD

**Issue by DJprasenjit** [holgerlembke/ESPFMfGK#1]
i uploaded the code to esp32 everything is working good but rename file is not working.

**Comment by holgerlembke** [comment]
Yes. Thanks for reporting the error.

Stupid mistake /me made.

I just uploaded a new version, (not a release) https://github.com/holgerlembke/ESPFMfGK/archive/refs/heads/main.zip

This version has the new windowed editor. I did want to do some more tests, but it seems stable.

**Comment by DJprasenjit** [comment]
thanks sir. this is a very good project i am tring to make a webserver related ws2812 led matrix project with the help of this unique project.

**Comment by DJprasenjit** [comment]
i uploaded the simple example and when i swiching to flash/FFat to SD MMC card option in the right side shows the Size of storage is only shows the Flash/FFat size. after swiching to sd card also showing the size of Flash/FFat

**Comment by holgerlembke** [comment]
Please update your ESP32 board software. This error has been fixed in latest 2.0.12 or so.

**Comment by DJprasenjit** [comment]
> Please update your ESP32 board software. This error has been fixed in latest 2.0.12 or so.

sorry sir i tested with 2.0.12 and the latest 2.0.13 version esp32 board but same issue . only shows the storage size of ffat or flash memory

**Comment by holgerlembke** [comment]
Can not verify this. But that is SD-Card only, not MMC. MMC is still in Mailbag...

![image](https://github.com/holgerlembke/ESPFMfGK/assets/2034993/5c705c66-7ca7-44fc-ae0f-ce8cf02d3732)

**Comment by DJprasenjit** [comment]
ok ok mine is SD_MMC Card. and its 16GB but when shows its size is 2.82GB
![image](https://github.com/holgerlembke/ESPFMfGK/assets/108330279/dc5a9571-e234-44da-a9de-2e9b2284c625)

**Comment by holgerlembke** [comment]
Well, that error has just been fixed.

Change this: String dispFileString(uint64_t fs, bool printorg) in .h and .cpp file.

**Comment by DJprasenjit** [comment]
thanks sir, now its showing the full size of sd mmc card . actually i am tring to make a project with it, i am lerning code but html, java script, css, web server these are new to me. can you help me to make it. it will be realy help full

**Comment by holgerlembke** [comment]
Sorry, no I can't help with html/css/js.

https://jsfiddle.net/  is a nice tool to get productive.
