### ISSUE TITLE
New Library

### ISSUE THREAD

**Issue by jameszah** [holgerlembke/ESPFMfGK#2]
Nice.

No dates and times on the files ?

A few things I was going to add to the old version.
- limit number of files per page to get quicker displays, with a "more files ... " button at bottom (I have a hundred files at times and just displaying the file list takes a long time)
- set up a system to edit a particular file without going through the file list page, so I could click a link from a webpage where I already know the filename and folder, and esp32 would immediately serve a page with the editing javascript and box to edit, and the save button and its javascript
- like this link appearing in a webpage http://192.168.4.1:8080/e?edit=config.txt

All that might be solved by just stuffing the  big group of files into a subfolder.

Does it read every file in the filesystem before displaying?  My sd modification ignored the subfolders before you looked into them.

**Comment by holgerlembke** [comment]
I'm currently unhappy with it. The flags-system to control what is visible and allow it a total mess, I dislike it deeply. So no new features until I have an idea about how to unconfuse it, make it more clear, streamline etc. 

Date and other file attributes (are there?) are on my list. But no new features.

Another thing you mention is that with F5 you lose all your open files, list settings etc, always starting at rooot. I want to change that, too. But no new features.

As far as I remember, it only reads the current folder (if on folder mode).

Last thing I did was a snap-in-interface to add arbitrary web controls into it. This example shows a on-esp32-c-compiler.

![bafkreigw6un2y5je6kdh73rdznc2l7qvvf6ys2tlwnot47am7myi4gxlfu](https://github.com/holgerlembke/ESPFMfGK/assets/2034993/d50ab2d3-7fe0-47c1-8974-d98113d3e31b)
