### ISSUE TITLE
Cannot compile, missing crc32.h

### ISSUE THREAD

**Issue by aaronw2** [holgerlembke/ESPFMfGK#6]
Arduino/libraries/ESP32_File_Manager_for_Generation_Klick_ESPFMfGK/src/ESPFMfGKGa.cpp:6:10: fatal error: crc32.h: No such file or directory
    6 | #include <crc32.h>
      |          ^~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by holgerlembke** [comment]
There is a file upcase/lowercase mitmatch. Please change to

 #include <CRC32.h>
